name: Go

on:
  push:
    branches: [ main, staging ]
  pull_request:
    branches: [ main, staging ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Migration
        run: |
          migrate -path db/migration -database "postgres://vysjvbplqhhnkq:a78c377957dbb1342f8e1932f03645a7ec6a8301397ccc14e4169ea05473bedc@ec2-54-170-163-224.eu-west-1.compute.amazonaws.com:5432/dfi5c1hhmnm8k4" -verbose up

      - name: Build
        run: go build -v ./...


      - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        name: Deploy to heroku
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/staging' }}
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "village-square" #Must be unique in Heroku
          heroku_email: ${{secrets.FRANKLYN_EMAIL}}
